version: '3'

networks: 
  ep-mern: 
    external: true

services:
  search-service:
    image: ep-mern-searchservice-testing:latest
    # image: ep-mern-searchservice:v3
    container_name: ep-mern-searchservice 
    # stdin_open: true
    environment:
      - API_KEY = S36HVZZjkZjRGm2FTSDwYkdrB5GsGne3
      - EVENT_MASTER_URL = https://app.ticketmaster.com/discovery/v2/events?apikey=S36HVZZjkZjRGm2FTSDwYkdrB5GsGne3
      - DEV_EVENT_MASTER_URL = http://localhost:8080/api/ticketmasterstub
      - PORT = 3002

    build:
      dockerfile: Dockerfile
      context: ./search-microservice
    volumes:
      - /api/node_modules
      - ./api:/app
    ports:
      - "3002:3002"