apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ep-searchservice-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /ms/search
        pathType: Prefix
        backend:
          service:
            name: ep-mern-searchservice
            port:
              number: 80